@startuml 簡易クラス図
スタート画面 -> 出題画面 : スタートボタンが押されたら
出題画面 -> 解答画面 : 出題が終わったら
解答画面 -> 結果画面 : 解答を間違えるか、全問正解したら
スタート画面 --> SakasaM : 桁数を渡す
出題画面 --> SakasaM : 数字列の取得
解答画面 --> SakasaM : 解答数字を送る
結果画面 --> SakasaM : 桁数と判定結果を取得
SakasaM -> QuestionArray
SakasaM -> Judgement

package スタート画面{
    class StartForm{
        Int 桁数
        桁数指定ボタン()
        スタートボタン()
        終了ボタン()
    }
}

package 出題画面{
    class QuestionForm{
        数字ラベル
    }
}

package 解答画面{
    class AnswerForm{
        数字ボタン()
    }
}

package 結果画面{
    class Clear/Overform{
        閉じるボタン()
    }
}

class SakasaM{
    出題数字列生成(桁数)
    正否判定(n桁目, 解答数字)
}

class QuestionArray{
    Int 桁数
    Int列ランダム生成(桁数)
    リバース関数()
}

class Judgement{
    Int n桁目
    IntArray 出題数字列
    正解判定(出題文字列[n桁目], 解答数字)
}