@startuml 状態遷移図
' state CountChecker <<choice>>
' state IntJudger <<choice>>

[*] --> IntAraay
IntAraay : 任意桁の整数配列を生成
IntAraay --> ShowInt
ShowInt : 上からひとつづつ表示
ShowInt --> ShowInt : [n < Array.Length]
ShowInt --> InputInt : [n >= Array.Length]
InputInt : 後ろからひとつづつ解答する

InputInt --> InputInt : [n == Array[i]]
InputInt --> ShowGameOver : [n != Array[i]]
ShowGameOver : 間違った瞬間ゲームオーバー
InputInt --> ShowGameCLear : [i >= Array.Length]
ShowGameCLear : 全て合っていたらゲームクリア

ShowGameOver --> [*]
ShowGameCLear --> [*]
@enduml
